server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cule?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true